### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by KatIsCoding** [lfmnovaes/portfolio#10]

**Comment by ramiaquista** [comment]
## Your project is awesome 😄

I think it would be a great idea if you can fix the mobile background img of the main section. I recommend trying to use a background-size: cover property, in order to make it as stretch as possible. 🔨

Well, Job ! 🎉

**Comment by KatIsCoding** [comment]
## I liked everything!

### But I still have suggestions for you I think would make your project look even better!

![image](https://user-images.githubusercontent.com/22417577/130981987-4345c6d5-d840-4605-9f73-9fcb2d3c2b60.png)

### I noticed you have a cool animation on every image of every project and it looks good! But, I don't think you are using it to its fullest! What about instead of triggering the animation when you hover the image, you do it when you hover the whole project "card" or "space", I think that way people will notice it even faster and will captivate some's attention!

![gif](https://media.giphy.com/media/ICOgUNjpvO0PC/giphy.gif)

**Comment by lfmnovaes** [comment]
I've implemented these suggestions, thank you.
